# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import proto.finance_pb2 as finance__pb2

GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in finance_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PaymentStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.MakePaynowDeposit = channel.unary_unary(
                '/Payment/MakePaynowDeposit',
                request_serializer=finance__pb2.PaynowPayload.SerializeToString,
                response_deserializer=finance__pb2.PaynowResponse.FromString,
                _registered_method=True)
        self.MakeCryptoDeposit = channel.unary_unary(
                '/Payment/MakeCryptoDeposit',
                request_serializer=finance__pb2.CryptoPayload.SerializeToString,
                response_deserializer=finance__pb2.CryptoResponse.FromString,
                _registered_method=True)


class PaymentServicer(object):
    """Missing associated documentation comment in .proto file."""

    def MakePaynowDeposit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MakeCryptoDeposit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PaymentServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'MakePaynowDeposit': grpc.unary_unary_rpc_method_handler(
                    servicer.MakePaynowDeposit,
                    request_deserializer=finance__pb2.PaynowPayload.FromString,
                    response_serializer=finance__pb2.PaynowResponse.SerializeToString,
            ),
            'MakeCryptoDeposit': grpc.unary_unary_rpc_method_handler(
                    servicer.MakeCryptoDeposit,
                    request_deserializer=finance__pb2.CryptoPayload.FromString,
                    response_serializer=finance__pb2.CryptoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Payment', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('Payment', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Payment(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def MakePaynowDeposit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Payment/MakePaynowDeposit',
            finance__pb2.PaynowPayload.SerializeToString,
            finance__pb2.PaynowResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MakeCryptoDeposit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Payment/MakeCryptoDeposit',
            finance__pb2.CryptoPayload.SerializeToString,
            finance__pb2.CryptoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
